name: example
description: A new Flutter project.

publish_to: "none"

version: 1.3.3+48

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  toastification:
    path: ../
  dart_style: ^2.3.2
  flutter_svg: ^2.0.6
  font_awesome_flutter: ^10.4.0
  flutter_sticky_header: ^0.6.5
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  responsive_framework: ^0.2.0
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  iconsax_flutter: ^1.0.0
  url_launcher: ^6.1.12
  google_fonts: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  flex_color_picker: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  freezed: ^2.3.4

flutter:
  uses-material-design: true

  fonts:
    - family: PlusJakartaDisplay
      fonts:
        - asset: fonts/PlusJakartaDisplay-Regular.otf
          weight: 400
        - asset: fonts/PlusJakartaDisplay-Medium.otf
          weight: 500
        - asset: fonts/PlusJakartaDisplay-Bold.otf
          weight: 700

  assets:
    - assets/img/
