name: toastification
description: Toastification is a Flutter package that allows you to easily show toast and notification messages in your application.
version: 1.0.0
homepage: https://payamzahedi.com/toastification/
repository: https://github.com/payam-zahedi/toastification

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  uuid: ^3.0.7
  pausable_timer: ^1.0.0+7
  collection: ^1.16.0
  iconsax_flutter: ^1.0.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
