name: toastification
description: Toastification is a Flutter package that allows you to easily show toast messages in your application.
version: 0.0.3
homepage: https://github.com/payam-zahedi/toastification

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  uuid: ^3.0.7
  pausable_timer: ^1.0.0+7
  collection: ^1.16.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
